# ==========================================
# 1. CONFIGURACIÓN DEL SERVIDOR
# ==========================================
spring.application.name=ms-bioequivalencia
server.port=8084

# ==========================================
# 2. CONEXIÓN A BASE DE DATOS LOCAL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691

# ==========================================
# 3. CONFIGURACIÓN DE HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true