services:
  # 1. LA BASE DE DATOS
  db-medimapa:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: medimapa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 753691
    ports:
      - "5432:5432"
    # Persistencia de datos
    volumes:
      - pgdata_medimapa:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medimapa_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. TUS MICROSERVICIOS INTERNOS
  ms-usuarios:
    build: ./ms-usuarios
    restart: on-failure 
    ports:
      - "8085:8085" # Exponemos el puerto hacia Windows
    depends_on:
      db-medimapa:
        condition: service_healthy
  
  ms-geocalizacion:
    build: ./ms-geocalizacion/geocalizacion
    restart: on-failure # Resiliencia ante caídas de DB
    depends_on:
      db-medimapa:
        condition: service_healthy

  ms-catalogo:
    build: ./ms-catalogo
    restart: on-failure # Resiliencia ante caídas de DB
    depends_on:
      db-medimapa:
        condition: service_healthy

  medimapa: # Tu Scraper con Playwright
    build: ./medimapa/medimapa
    restart: on-failure # Resiliencia ante caídas de DB
    depends_on:
      db-medimapa:
        condition: service_healthy

  # 3. LA PUERTA AL MUNDO (API GATEWAY)
  api-gateway:
    build: ./api-gateway
    restart: on-failure # Autocorrección de red
    ports:
      - "8080:8080" # Expone el puerto del backend a internet
    depends_on:
      - ms-usuarios
      - ms-catalogo
      - ms-geocalizacion
      - medimapa

  # 4. TU APLICACIÓN WEB (FRONTEND)
  frontend:
    build: ./MediMapUI/MediMapUI/portal-web 
    restart: on-failure # Tolerancia a fallos de Nginx
    ports:
      - "5173:80"

  newman-ms-usuarios:
    image: postman/newman:latest
    restart: "no"
    depends_on:
      - api-gateway
    volumes:
      - ./ms-usuarios_tests.json:/etc/newman/ms-usuarios_tests.json:ro
    command: ["run", "/etc/newman/ms-usuarios_tests.json", "--delay-request", "50", "--reporters", "cli"]

  newman-ms-catalogo:
    image: postman/newman:latest
    restart: "no"
    depends_on:
      - api-gateway
    volumes:
      - ./ms-catalogo_tests.json:/etc/newman/ms-catalogo_tests.json:ro
    command: ["run", "/etc/newman/ms-catalogo_tests.json", "--delay-request", "50", "--reporters", "cli"]

  newman-ms-geocalizacion:
    image: postman/newman:latest
    restart: "no"
    depends_on:
      - api-gateway
    volumes:
      - ./ms-geocalizacion_tests.json:/etc/newman/ms-geocalizacion_tests.json:ro
    command: ["run", "/etc/newman/ms-geocalizacion_tests.json", "--delay-request", "50", "--reporters", "cli"]

  newman-ms-medimapa:
    image: postman/newman:latest
    restart: "no"
    depends_on:
      - api-gateway
    volumes:
      - ./ms-medimapa_tests.json:/etc/newman/ms-medimapa_tests.json:ro
    command: ["run", "/etc/newman/ms-medimapa_tests.json", "--delay-request", "50", "--reporters", "cli"]

# DECLARACIÓN DEL VOLUMEN GLOBAL
volumes:
  pgdata_medimapa: