services:
  # 1. LA BASE DE DATOS
  db-medimapa:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: medimapa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 753691
    ports:
      - "5432:5432"
    volumes:
      - pgdata_medimapa:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medimapa_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. TUS MICROSERVICIOS INTERNOS
  ms-usuarios:
    build: ./ms-usuarios
    restart: on-failure 
    ports:
      - "8085:8085" 
    depends_on:
      db-medimapa:
        condition: service_healthy
  
  ms-geocalizacion:
    build: ./ms-geocalizacion/geocalizacion
    restart: on-failure 
    depends_on:
      db-medimapa:
        condition: service_healthy

  ms-catalogo:
    build: ./ms-catalogo
    restart: on-failure 
    depends_on:
      db-medimapa:
        condition: service_healthy

  medimapa: # scraper con Playwright
    build: ./medimapa/medimapa
    restart: on-failure 
    depends_on:
      db-medimapa:
        condition: service_healthy

  # 3. API GATEWAY
  api-gateway:
    build: ./api-gateway
    restart: on-failure 
    ports:
      - "8080:8080" # Expone el puerto del backend a internet
    depends_on:
      - ms-usuarios
      - ms-catalogo
      - ms-geocalizacion
      - medimapa

  # 4.  APLICACIÓN WEB
  frontend:
    build: ./MediMapUI/MediMapUI/portal-web 
    restart: on-failure 
    ports:
      - "5173:80"

volumes:
  pgdata_medimapa: