# 1. Usamos la imagen oficial de Microsoft Playwright con Java preinstalado
FROM mcr.microsoft.com/playwright.java:v1.43.0-jammy

# 2. Creamos una carpeta para nuestro código
WORKDIR /app

# 3. Copiamos los archivos de tu proyecto al contenedor
COPY pom.xml .
COPY src ./src
COPY mvnw .
COPY .mvn ./.mvn

# 4. Le damos permisos al ejecutable de Maven
RUN chmod +x ./mvnw

# 5. Compilamos tu proyecto (saltando los tests para que sea rápido)
RUN ./mvnw clean package -DskipTests

# 6. Ejecutamos el microservicio (Reemplaza el nombre del .jar por el tuyo)
CMD ["java", "-jar", "target/ms-scraper-0.0.1-SNAPSHOT.jar"]