# Nuevo puerto para el Microservicio de Usuarios (Módulo 4)
server.port=8085

spring.application.name=ms-usuarios

# Conexión a tu Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://db-medimapa:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691
spring.datasource.driver-class-name=org.postgresql.Driver

# Aumentar el limite de subida de archivos (Excel ISP)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Hibernate: Esto creará las tablas automáticamente
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true