# Nuevo puerto para el Microservicio de Usuarios (Módulo 4)
server.port=8085

spring.application.name=ms-usuarios

# Conexión a tu Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: Esto creará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true