spring.application.name=ms-catalogo
server.port=8081

spring.datasource.url=jdbc:postgresql://db-medimapa:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691

# 🔥 Tratado de Paz: Este microservicio solo leerá, no intentará modificar las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.continue-on-error=true