# ==========================================
# 1. CONFIGURACIÓN DEL SERVIDOR
# ==========================================
spring.application.name=ms-catalogo
server.port=8081

# ==========================================
# 2. CONEXIÓN A BASE DE DATOS LOCAL
# ==========================================
spring.datasource.url=jdbc:postgresql://db-medimapa:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691

# ==========================================
# 3. CONFIGURACIÓN DE HIBERNATE
# ==========================================
# Usamos el dialecto normal, NO el spatial
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true