server:
  port: 8080 # El Gateway siempre es el 8080

spring:
  # aumento de espacio para excels
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  codec:
    max-in-memory-size: 50MB

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 120s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173" # React
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # RUTA 1: CATALOGO (Responde medicamentos y sucursales)
        - id: ms-catalogo-route
          uri: http://ms-catalogo:8081
          predicates:
            - Path=/api/medicamentos/**, /api/sucursales/**

        # RUTA 2: SCRAPER
        - id: medimapa-scraper-route
          uri: http://medimapa:8082
          predicates:
            - Path=/api/scraper/**
            
        # RUTA 3: MICROSERVICIO GEOLOCALIZACIÓN
        - id: ms-geo-route
          uri: http://ms-geocalizacion:8083
          predicates:
            - Path=/api/v1/geolocalizacion/**

        # RUTA 4: MICROSERVICIO USUARIOS (y Buscador en Vivo)
        - id: ms-usuarios-route
          uri: http://ms-usuarios:8085
          predicates:
            - Path=/api/usuarios/**, /api/buscador/**