spring.application.name=medimapa

spring.datasource.url=jdbc:postgresql://localhost:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true