server.port=8083
spring.application.name=ms-geocalizacion

spring.datasource.url=jdbc:postgresql://db-medimapa:5432/medimapa_db
spring.datasource.username=postgres
spring.datasource.password=753691

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Fuerza la carga de datos sin usar dialectos manuales
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.continue-on-error=true